steps:
  # 1. Install dependencies
  - name: 'oven/bun:1'
    id: 'install'
    entrypoint: 'bun'
    args: ['install', '--frozen-lockfile']

  # 2. Lint & Test
  - name: 'oven/bun:1'
    id: 'test'
    entrypoint: 'bun'
    args: ['run', 'turbo', 'run', 'test', 'lint']
    waitFor: ['install']

  # 3. Build Docker images (parallel)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ingestion'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/ingestion:$SHORT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/ingestion:latest', '-f', 'apps/ingestion/Dockerfile', '.']
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-memory'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/memory:$SHORT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/memory:latest', '-f', 'apps/memory/Dockerfile', '.']
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-search'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/search:$SHORT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/search:latest', '-f', 'apps/search/Dockerfile', '.']
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-execution'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/execution:$SHORT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/execution:latest', '-f', 'apps/execution/Dockerfile', '.']
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-control'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/control:$SHORT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/control:latest', '-f', 'apps/control/Dockerfile', '.']
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-interface'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/interface:$SHORT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/interface:latest', '-f', 'apps/interface/Dockerfile', '.']
    waitFor: ['test']

  # 4. Push Docker images (parallel)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ingestion'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/ingestion']
    waitFor: ['build-ingestion']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-memory'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/memory']
    waitFor: ['build-memory']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-search'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/search']
    waitFor: ['build-search']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-execution'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/execution']
    waitFor: ['build-execution']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-control'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/control']
    waitFor: ['build-control']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-interface'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/interface']
    waitFor: ['build-interface']

  # 5. Deploy to Cloud Run (parallel)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-ingestion'
    entrypoint: gcloud
    args: ['run', 'deploy', 'ingestion', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/ingestion:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed']
    waitFor: ['push-ingestion']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-memory'
    entrypoint: gcloud
    args: ['run', 'deploy', 'memory', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/memory:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed']
    waitFor: ['push-memory']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-search'
    entrypoint: gcloud
    args: ['run', 'deploy', 'search', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/search:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed']
    waitFor: ['push-search']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-execution'
    entrypoint: gcloud
    args: ['run', 'deploy', 'execution', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/execution:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed']
    waitFor: ['push-execution']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-control'
    entrypoint: gcloud
    args: ['run', 'deploy', 'control', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/control:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed']
    waitFor: ['push-control']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-interface'
    entrypoint: gcloud
    args: ['run', 'deploy', 'interface', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/interface:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed', '--port', '3000']
    waitFor: ['push-interface']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/ingestion:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/memory:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/search:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/execution:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/control:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/engram-repo/interface:$SHORT_SHA'
